<?php
/**
 * @file
 * Provide views data for our custom module_name.
 */

use Drupal\field\FieldStorageConfigInterface;

/**
 * Implements hook_field_views_data_alter).
 */
function views_list_sort_field_views_data_alter(array &$data, FieldStorageConfigInterface $field_storage) {
  if ($field_storage->getType() == 'list_string') {
    foreach ($data as $table_name => $table_data) {
      $data[$table_name][$field_storage->getName() . '_value']['sort']['id'] = 'sort_allowed_values';
    }
  }
}
